version: '3.9'

services:
  # Go web application service
  app:
    build:
      context: .
    ports:
      - "8080:80"
    depends_on:
      - db

  # Redis database service
  db:
    image: redis:latest
    volumes:
      - redis_data:/data    
    ports:
      - "6379:6379"

volumes:
  redis_data:
