version: "3.8"
services:
  web:
    build: .
    command: python app.py
    ports:
      - target: 5000
        published: 5000
    networks:
      - counter-net
    volumes:
      - type: volume
        source: counter-vol
        target: /usr/src/app
    container_name: web
    depends_on:
      - "db"

  db:
    image: "redis:alpine"
    networks:
      counter-net:
    container_name: db

networks:
  counter-net:

volumes:
  counter-vol: