version: "3.8"
services:
  web-fe:
    image: maroskukan/nodejs-sample:swarm
    command: python app.py
    deploy:
      replicas: 10
    ports:
      - target: 8080
        published: 5000
    networks:
      - counter-net
    volumes:
      - type: volume
        source: counter-vol
        target: /code
  redis:
    image: "redis:alpine"
    networks:
      counter-net:

networks:
  counter-net:

volumes:
  counter-vol: